/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fabrica;
import java.util.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/**
 *
 * @author lucas
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    Sala fabrica;
    Robo posicao;
    Navegacao navegacao;
    Obstaculos[] obstaculos;
    public MainFrame(Sala fabrica, Robo posicao, Navegacao navegacao, Obstaculos[] obstaculos) { //Construtor da interface
        initComponents();
        this.fabrica=fabrica;
        this.posicao=posicao;
        this.navegacao=navegacao;
        this.obstaculos=obstaculos;
        refreshGrid();
        linhas();
        colunas();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        mapa = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cenário do Robô");
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setSize(new java.awt.Dimension(1024, 768));

        jPanel1.setBackground(new java.awt.Color(105, 134, 191));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 768));

        jPanel2.setBackground(new java.awt.Color(19, 45, 70));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Insira as coordenadas do robô:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Insira as coordenadas do obstáculo:");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Insira o destino:");

        jButton1.setBackground(new java.awt.Color(105, 134, 191));
        jButton1.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(105, 134, 191));
        jButton2.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(105, 134, 191));
        jButton3.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("X:");

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Y:");

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("X:");

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Y:");

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("X:");

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Y:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(142, 142, 142)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(256, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(105, 134, 191));
        jPanel4.setLayout(new java.awt.GridLayout(21, 1));

        jPanel5.setBackground(new java.awt.Color(105, 134, 191));
        jPanel5.setLayout(new java.awt.GridLayout(1, 21));

        mapa.setPreferredSize(new java.awt.Dimension(700, 700));
        mapa.setLayout(new java.awt.GridLayout(21, 21));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mapa, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mapa, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1025, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    //Metodo para lidar com a interacao com o botao de posicionar robo
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {//Bloco try catch para manipulacao de erros
                    int i = Integer.parseInt(jTextField1.getText()); //Entrada da coordenada x do robo
                    int j = Integer.parseInt(jTextField2.getText()); //Entrada da coordenada y do robo
                    jTextField1.setText(""); //Limpar a caixa de texto
                    jTextField2.setText("");
                    if (fabrica.dentroDosLimites(i, j)) {
                        if(fabrica.getSala()[i-1][j-1]==2){// Se houver um obstaculo, aparece um aviso e o robo nao eh posicionado
                            JOptionPane.showMessageDialog(this, "Existe um obstáculo nessa posição", "Aviso", JOptionPane.WARNING_MESSAGE);
                        }else{//Posiciona o robo e atualiza o cenario
                                posicao.setIJ(i - 1, j - 1);
                                refreshGrid();
                        }
                            
                    } 
                    else {//Se a entrada for um valor inteiro mas estiver fora dos limites ou for negativa, aparece um aviso
                        JOptionPane.showMessageDialog(this, "Fora dos limites", "Aviso", JOptionPane.WARNING_MESSAGE);
                    }
                } catch (NumberFormatException ex) {//Caso tenha uma entrada invalida, aparece um aviso de erro
                    JOptionPane.showMessageDialog(this, "Entrada inválida", "Erro", JOptionPane.ERROR_MESSAGE);
                    jTextField1.setText("");
                    jTextField2.setText("");
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {//Bloco try catch para manipulacao de erros
                    int i = Integer.parseInt(jTextField3.getText());//Entrada da coordenada x do obstaculo
                    int j = Integer.parseInt(jTextField4.getText());//Entrada da coordenada x do obstaculo
                    jTextField3.setText("");//Limpar a caixa de texto
                    jTextField4.setText("");
                    if (fabrica.dentroDosLimites(i, j)) {
                        if(fabrica.getSala()[i-1][j-1]==2){// Se houver um obstaculo, aparece um aviso e o obstaculo nao eh posicionado
                            JOptionPane.showMessageDialog(this, "Já existe um obstáculo nessa posição", "Aviso", JOptionPane.WARNING_MESSAGE);
                        }
                        else if(fabrica.getSala()[i-1][j-1]==1){// Se houver um robo, aparece um aviso e o obstaculo nao eh posicionado
                            JOptionPane.showMessageDialog(this, "Já existe um robô nessa posição", "Aviso", JOptionPane.WARNING_MESSAGE);
                        }
                        else{//Posiciona o obstaculo e atualiza o cenario
                            obstaculos[fabrica.getQuantAtualObstaculos()] = new Obstaculos(fabrica);
                            obstaculos[fabrica.getQuantAtualObstaculos()].setIJ(i - 1, j - 1);
                            refreshGrid();
                        }
                        
                    } else {//Se a entrada for um valor inteiro mas estiver fora dos limites ou for negativa, aparece um aviso
                        JOptionPane.showMessageDialog(this, "Fora dos limites", "Aviso", JOptionPane.WARNING_MESSAGE);
                    }
                } catch (NumberFormatException ex) {//Caso tenha uma entrada invalida, aparece um aviso de erro
                    JOptionPane.showMessageDialog(this, "Entrada inválida", "Erro", JOptionPane.ERROR_MESSAGE);
                    jTextField3.setText("");//Limpar a caixa de texto
                    jTextField4.setText("");
                }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{//Bloco try catch para manipulacao de erros
            int i = Integer.parseInt(jTextField5.getText());//Entrada da coordenada x do destino
            int j = Integer.parseInt(jTextField6.getText());//Entrada da coordenada x do destino
            jTextField5.setText("");//Limpar a caixa de texto
            jTextField6.setText("");
            i--;
            j--;
            if(fabrica.dentroDosLimites(i, j)){
                if(fabrica.getSala()[i][j]==2){// Se houver um obstaculo, aparece um aviso e o robo nao se movimenta
                    JOptionPane.showMessageDialog(this, "Existe um obstáculo nessa posição", "Aviso", JOptionPane.WARNING_MESSAGE);
                }
                else if (!posicao.getPosicionado()){// Se o robo ainda nao estiver posicionado, aparece um aviso e o robo nao se movimenta
                    JOptionPane.showMessageDialog(this, "O robô ainda não está posicionado", "Aviso", JOptionPane.WARNING_MESSAGE);
                }
                else{
                    int chegada = navegacao.coordenadas_para_posicao(i, j);//Transforma a coordenada de destino em um numero que representa a posicao
                    int posX = posicao.getI();
                    int posY = posicao.getJ();
                    int partida = navegacao.coordenadas_para_posicao(posX, posY);//Transforma a coordenada de origem em um numero que representa a posicao
                    java.util.List<Integer> path = navegacao.encontrarCaminhoBFS(partida, chegada);//Chamada da busca em largura para encontrar um caminho
                    System.out.printf("I: %d J: %d Chegada: %d", i, j, chegada);
                    System.out.printf("X: %d Y: %d Partida: %d", posX, posY, partida);
                    System.out.println(path);
                    if (!path.isEmpty()) {
                    javax.swing.Timer timer = new javax.swing.Timer(200, new ActionListener() {//Timer para adicionar um delay entre cada movimentacao do robo
                        int index = 0;

                        @Override
                        public void actionPerformed(ActionEvent e) {
                            if (index < path.size()) {
                                int at = path.get(index);//Recebe o numero de um dos passos do caminho
                                int x = navegacao.coordenada_x(at);//Transformando esse numero em coordenada
                                int y = navegacao.coordenada_y(at);
                                if (fabrica.dentroDosLimites(x, y)) {
                                    posicao.setIJ(x, y);//Posicionando o robo na proxima posicao 
                                    refreshGrid();//Atualiza o cenario
                                    System.out.println("X: " + x + " Y: " + y);
                                    System.out.println(at);
                                    index++;
                                }
                            } else {
                                ((javax.swing.Timer) e.getSource()).stop(); 
                            }
                        }
                    });
                    timer.start(); 
                }
                    else{//Caso nao exista um caminho, o aviso sera mostrado
                        JOptionPane.showMessageDialog(this, "Não existe um caminho para a coordenada fornecida", "Aviso", JOptionPane.WARNING_MESSAGE);
                    }
                }
            }
            else {//Se a entrada for um valor inteiro mas estiver fora dos limites ou for negativa, aparece um aviso
                    JOptionPane.showMessageDialog(this, "Fora dos limites", "Aviso", JOptionPane.WARNING_MESSAGE);
                 }
        }catch (NumberFormatException ex) {//Caso tenha uma entrada invalida, aparece um aviso de erro
                    JOptionPane.showMessageDialog(this, "Entrada inválida", "Erro", JOptionPane.ERROR_MESSAGE);
                    jTextField5.setText("");//Limpar a caixa de texto
                    jTextField6.setText("");
        }
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(fabrica.getSala()[posicao.getI()+1][posicao.getJ()]!=2 && posicao.getPosicionado()){//Metodo para movimentar para cima, caso possivel
            posicao.mover_para_baixo();
            refreshGrid();
        }
        else if (!posicao.getPosicionado()){//Se o robo nao estiver posicionado, um aviso eh mostrado
            JOptionPane.showMessageDialog(this, "O robô ainda nao está posicionado", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        else{//Se houver um obstaculo no caminho, o robo nao se move e um aviso e mostrado
             JOptionPane.showMessageDialog(this, "Existe um obstáculo nessa direção", "Aviso", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(fabrica.getSala()[posicao.getI()][posicao.getJ()+1]!=2 && posicao.getPosicionado()){
            posicao.mover_para_direita();
            refreshGrid();
        }
        else if (!posicao.getPosicionado()){//Se o robo nao estiver posicionado, um aviso eh mostrado
            JOptionPane.showMessageDialog(this, "O robô ainda nao está posicionado", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        else{//Se houver um obstaculo no caminho, o robo nao se move e um aviso e mostrado
            JOptionPane.showMessageDialog(this, "Existe um obstáculo nessa direção", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(posicao.getI()==0){//Evitar erro em relacao a matriz
            JOptionPane.showMessageDialog(this, "O robô ainda nao está posicionado", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        else if(fabrica.getSala()[posicao.getI()-1][posicao.getJ()]!=2 && posicao.getPosicionado()){
            posicao.mover_para_cima();
            refreshGrid();
        }
        else if (!posicao.getPosicionado()){//Se o robo nao estiver posicionado, um aviso eh mostrado
            JOptionPane.showMessageDialog(this, "O robô ainda nao está posicionado", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        else{//Se houver um obstaculo no caminho, o robo nao se move e um aviso e mostrado
            JOptionPane.showMessageDialog(this, "Existe um obstáculo nessa direção", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(posicao.getJ()==0){//Evitar erro em relacao a matriz
            JOptionPane.showMessageDialog(this, "O robô ainda nao está posicionado", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        else if(fabrica.getSala()[posicao.getI()][posicao.getJ()-1]!=2 && posicao.getPosicionado()){
            posicao.mover_para_esquerda();
            refreshGrid();
        }
        else if (!posicao.getPosicionado()){//Se o robo nao estiver posicionado, um aviso eh mostrado
            JOptionPane.showMessageDialog(this, "O robô ainda nao está posicionado", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        else{//Se houver um obstaculo no caminho, o robo nao se move e um aviso e mostrado
            JOptionPane.showMessageDialog(this, "Existe um obstáculo nessa direção", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed
   
    private void setIcon(){//Metodo para setar o icone do robo barra de tarefas e na barra superior
        ImageIcon originalIcon = new ImageIcon(getClass().getResource("/images/65508.png"));           
        Image originalImage = originalIcon.getImage();
        Image scaledImage = originalImage.getScaledInstance(30, 30, Image.SCALE_SMOOTH);  // Ajuste o tamanho conforme necessário
        setIconImage(scaledImage);
    }
    
    public void linhas() {//Metodo para preencher a linha de coordenadas na interface
        jPanel4.removeAll();
        for (int i = 1; i <= 21; i++) {
            JLabel label = new JLabel("", SwingConstants.CENTER);
            String linha = String.valueOf(i);
            label.setText(linha); 
            label.setBackground(Color.getColor("6986BF"));
            label.setForeground(Color.BLACK);
            label.setOpaque(true);//Garante que o fundo dos labels seja desenhado com a cor especificada
            jPanel4.add(label);
        }
        jPanel4.revalidate();//Garante a atualizacao do tamanho e das posicoes dos componentes presentes no panel
        jPanel4.repaint();//Garante a atualizacao das mudancas visuais dos componentes presentes no panel
    }
    
    public void colunas() {//Metodo para preencher a coluna de coordenadas na interface
        jPanel5.removeAll();
        for (int i = 1; i <= 21; i++) {
            JLabel label = new JLabel("", SwingConstants.CENTER);
            String linha = String.valueOf(i);
            label.setText(linha); 
            
            label.setBackground(Color.getColor("6986BF"));
            label.setForeground(Color.BLACK);
            label.setOpaque(true);//Garante que o fundo dos labels seja desenhado com a cor especificada
            jPanel5.add(label);
        }
        jPanel5.revalidate();//Garante a atualizacao do tamanho e das posicoes dos componentes presentes no panel
        jPanel5.repaint();//Garante a atualizacao das mudancas visuais dos componentes presentes no panel
    }
    
    public void refreshGrid() {//Metodo para preencher o panel com os labels que representam os obstaculos, espaços vazios e o robo
        mapa.removeAll();
        int[][] sala = fabrica.getSala();
        for (int i = 0; i < 21; i++) {
            for (int j = 0; j < 21; j++) {
                JLabel label = new JLabel("", SwingConstants.CENTER);
                label.setBorder(BorderFactory.createLineBorder(Color.GRAY));
                if (sala[i][j] == 1) {
                    //label.setText("R");
                    //ImageIcon originalIcon = new ImageIcon("/home/lucas/Área de Trabalho/Robo/RoboEmPe.png");  
                    ImageIcon originalIcon = new ImageIcon(getClass().getResource("/images/RoboEmPe.png")); //Busca a imagem na pasta resource 
                    Image originalImage = originalIcon.getImage();
                    Image scaledImage = originalImage.getScaledInstance(30, 30, Image.SCALE_SMOOTH);  
                    ImageIcon robotIcon = new ImageIcon(scaledImage);
                    
                    label.setIcon(robotIcon);//Apos as manipulacoes necessarias, insere a imagem do robo no label
                    label.setBackground(Color.WHITE);
                } else if (sala[i][j] == 2) {
                    label.setText(" ");
                    label.setBackground(Color.BLACK);
                }
                label.setOpaque(true);//Garante que o fundo dos labels seja desenhado com a cor especificada
                mapa.add(label);
            }
        }
        mapa.revalidate();//Garante a atualizacao do tamanho e das posicoes dos componentes presentes no panel
        mapa.repaint();//Garante a atualizacao das mudancas visuais dos componentes presentes no panel
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JPanel mapa;
    // End of variables declaration//GEN-END:variables
}
